import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { listingText, now, readDomain, writeDomain } from "../listing-data.js";
import { locale, t } from "../i18n.js";
registerMainMenuItem({ label: "Каталог", labelKey: "menuCatalog", data: "catalog:search", order: 20 });
const composer = new Composer<Ctx>();
async function show(ctx: Ctx, query = "", sort = "new") { const data = await readDomain(ctx); let items = data.listings.filter((x) => !x.archived && `${x.title} ${x.description} ${x.location} ${x.propertyType}`.toLowerCase().includes(query.toLowerCase())); items = [...items].sort((a, b) => sort === "price" ? a.price - b.price : b.postedAt.localeCompare(a.postedAt)); if (!items.length) { await ctx.reply(await t(ctx, "emptyCatalog"), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "menuSubmit"), "submit:start")], [inlineButton(await t(ctx, "back"), "menu:main")]]) }); return; } const l = await locale(ctx); await ctx.reply(await t(ctx, "chooseListing"), { reply_markup: inlineKeyboard([...items.slice(0, 8).map((x) => [inlineButton(`${x.title} · ${x.price.toLocaleString(l === "ru" ? "ru-RU" : "en-US")}`, `catalog:view:${x.id}`)]), [inlineButton(await t(ctx, "newest"), "catalog:sort:new"), inlineButton(await t(ctx, "lowest"), "catalog:sort:price")], [inlineButton(await t(ctx, "searchAgain"), "catalog:query"), inlineButton(await t(ctx, "back"), "menu:main")]]) }); }
composer.callbackQuery("catalog:search", async (ctx) => { await ctx.answerCallbackQuery(); await show(ctx); });
composer.callbackQuery("catalog:query", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.step = "catalog:query"; await ctx.reply(await t(ctx, "searchAsk"), { reply_markup: { force_reply: true, input_field_placeholder: await t(ctx, "searchHint") } }); });
composer.callbackQuery(/^catalog:sort:(new|price)$/, async (ctx) => { await ctx.answerCallbackQuery(); await show(ctx, "", ctx.match![1]); });
composer.callbackQuery(/^catalog:view:(l\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const l = (await readDomain(ctx)).listings.find((x) => x.id === ctx.match![1] && !x.archived); if (!l) { await ctx.reply(await t(ctx, "unavailable")); return; } await ctx.reply(listingText(l, await locale(ctx)), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "contact"), `contact:init:${l.id}`), inlineButton(await t(ctx, "report"), `report:listing:${l.id}`)], [inlineButton(await t(ctx, "browse"), "catalog:search")]]) }); });
composer.callbackQuery(/^contact:init:(l\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.step = "contact:message"; ctx.session.draft = { listingId: ctx.match![1] }; await ctx.reply(await t(ctx, "contactAsk"), { reply_markup: { force_reply: true, input_field_placeholder: await t(ctx, "contactHint") } }); });
composer.on("message:text", async (ctx, next) => { if (ctx.session.step === "catalog:query") { ctx.session.step = "idle"; await show(ctx, ctx.message.text.trim()); return; } if (ctx.session.step !== "contact:message") return next(); const listingId = String(ctx.session.draft?.listingId ?? ""); const data = await readDomain(ctx); const l = data.listings.find((x) => x.id === listingId); if (!l) { await ctx.reply(await t(ctx, "unavailable")); return; } data.chats.push({ listingId, from: String(ctx.from?.id ?? ""), text: ctx.message.text.trim(), at: now().toISOString() }); await writeDomain(ctx, data); ctx.session.step = "idle"; try { await ctx.api.sendMessage(l.ownerChatId, await t(ctx, "ownerMessage", { message: ctx.message.text.trim() })); } catch {} await ctx.reply(await t(ctx, "relayed")); });
export default composer;
