import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { nextId, now, readDomain, writeDomain } from "../listing-data.js";
import { t } from "../i18n.js";
registerMainMenuItem({ label: "Пожаловаться", labelKey: "menuReport", data: "report:start", order: 40 });
const composer = new Composer<Ctx>();
async function choose(ctx: Ctx) { const listings = (await readDomain(ctx)).listings.filter((l) => !l.archived); if (!listings.length) { await ctx.reply(await t(ctx, "noReports")); return; } await ctx.reply(await t(ctx, "chooseReport"), { reply_markup: inlineKeyboard([...listings.slice(0, 8).map((l) => [inlineButton(l.title, `report:listing:${l.id}`)]), [inlineButton(await t(ctx, "back"), "menu:main")]]) }); }
composer.callbackQuery("report:start", async (ctx) => { await ctx.answerCallbackQuery(); await choose(ctx); });
composer.callbackQuery("moderation:reports", async (ctx) => { await ctx.answerCallbackQuery(); const chat = ctx.chat; if (!chat || chat.type === "private" || !ctx.from) { await ctx.reply(await t(ctx, "moderationGroup")); return; } try { const member = await ctx.api.getChatMember(chat.id, ctx.from.id); if (member.status !== "administrator" && member.status !== "creator") { await ctx.reply(await t(ctx, "moderationOnly")); return; } } catch { await ctx.reply(await t(ctx, "moderationCheck")); return; } const data = await readDomain(ctx); const titles = data.reports.slice(-10).map((r) => data.listings.find((l) => l.id === r.listingId)?.title).filter(Boolean).join("\n"); await ctx.reply(titles ? await t(ctx, "reportQueue", { titles }) : await t(ctx, "reportQueueEmpty")); });
composer.callbackQuery(/^report:listing:(l\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.draft = { listingId: ctx.match![1] }; await ctx.reply(await t(ctx, "issue"), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "duplicateReason"), "report:reason:duplicate"), inlineButton(await t(ctx, "misleading"), "report:reason:misleading")], [inlineButton(await t(ctx, "scam"), "report:reason:scam")]]) }); });
composer.callbackQuery(/^report:reason:(duplicate|misleading|scam)$/, async (ctx) => { await ctx.answerCallbackQuery(); const data = await readDomain(ctx); const listing = data.listings.find((x) => x.id === String(ctx.session.draft?.listingId ?? "")); if (!listing) { await ctx.reply(await t(ctx, "unavailable")); return; } data.reports.push({ id: nextId(data, "r"), reporter: String(ctx.from?.id ?? ""), listingId: listing.id, reason: ctx.match![1], timestamp: now().toISOString() }); listing.archived = true; await writeDomain(ctx, data); ctx.session.draft = undefined; if (ctx.chat && ctx.chat.type !== "private") try { await ctx.api.sendMessage(ctx.chat.id, await t(ctx, "moderatorAlert")); } catch {} await ctx.reply(await t(ctx, "thanksReport")); });
export default composer;
