import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { day, fingerprint, listingText, matches, nextId, now, readDomain, writeDomain, type Listing } from "../listing-data.js";
import { locale, t } from "../i18n.js";
registerMainMenuItem({ label: "Разместить объявление", labelKey: "menuSubmit", data: "submit:start", order: 10 });
const composer = new Composer<Ctx>();
const ask = async (ctx: Ctx, step: string, key: "titleAsk" | "descriptionAsk" | "priceAsk" | "locationAsk", hint: "titleHint" | "descriptionHint" | "priceHint" | "locationHint") => { ctx.session.step = step; await ctx.reply(await t(ctx, key), { reply_markup: { force_reply: true, input_field_placeholder: await t(ctx, hint) } }); };
const back = async (ctx: Ctx) => inlineKeyboard([[inlineButton(await t(ctx, "back"), "menu:main")]]);
composer.callbackQuery("submit:start", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.draft = { photos: [] }; ctx.session.step = "submit:photos"; await ctx.reply(await t(ctx, "sendPhotos"), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "continue"), "submit:photos:done")], [inlineButton(await t(ctx, "back"), "menu:main")]]) }); });
composer.on("message:photo", async (ctx, next) => { if (ctx.session.step !== "submit:photos") return next(); const photos = (ctx.session.draft?.photos as string[] | undefined) ?? []; photos.push(ctx.message.photo.at(-1)!.file_id); ctx.session.draft = { ...ctx.session.draft, photos }; await ctx.reply(await t(ctx, "photoAdded")); });
composer.callbackQuery("submit:photos:done", async (ctx) => { await ctx.answerCallbackQuery(); await ask(ctx, "submit:title", "titleAsk", "titleHint"); });
composer.callbackQuery(/^submit:type:(apartment|house|room|other)$/, async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.draft = { ...ctx.session.draft, propertyType: ctx.match![1] }; const bed = await awaitedBed(ctx); await ctx.reply(await t(ctx, "bedsAsk"), { reply_markup: inlineKeyboard([[1, 2, 3, 4].map((n) => inlineButton(`${n} ${bed}`, `submit:beds:${n}`)), [inlineButton(await t(ctx, "back"), "menu:main")]]) }); });
async function awaitedBed(ctx: Ctx) { return (await locale(ctx)) === "ru" ? "сп." : "bed"; }
composer.callbackQuery(/^submit:beds:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.draft = { ...ctx.session.draft, bedrooms: Number(ctx.match![1]) }; const d = ctx.session.draft as Record<string, unknown>; const text = `${d.title}\n${d.location} · ${d.propertyType} · ${d.bedrooms} ${(await locale(ctx)) === "ru" ? "сп." : "bed"}\n${Number(d.price).toLocaleString((await locale(ctx)) === "ru" ? "ru-RU" : "en-US")}\n${d.description}`; ctx.session.step = "submit:confirm"; await ctx.reply(await t(ctx, "preview", { listing: text }), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "publish"), "submit:confirm")], [inlineButton(await t(ctx, "cancel"), "menu:main")]]) }); });
composer.callbackQuery("submit:confirm", async (ctx) => { await ctx.answerCallbackQuery(); const d = ctx.session.draft as Record<string, unknown> | undefined; if (!d || !d.title || !d.description || !d.price || !d.location || !d.propertyType || !d.bedrooms) { await ctx.reply(await t(ctx, "incomplete"), { reply_markup: await back(ctx) }); return; } const data = await readDomain(ctx); const price = Number(d.price); const fp = fingerprint(String(d.title), String(d.location), price); let listing = data.listings.find((l) => l.fingerprint === fp); if (listing) { ctx.session.step = "idle"; await ctx.reply(await t(ctx, "duplicate")); return; } listing = { id: nextId(data, "l"), owner: String(ctx.from?.id ?? ""), ownerChatId: ctx.chat!.id, title: String(d.title), description: String(d.description), photos: (d.photos as string[]) ?? [], price, location: String(d.location), propertyType: String(d.propertyType), bedrooms: Number(d.bedrooms), source: "submission", postedAt: now().toISOString(), fingerprint: fp } satisfies Listing; data.listings.push(listing); ctx.session.step = "idle"; ctx.session.draft = undefined; await ctx.reply(await t(ctx, "live", { listing: listingText(listing, await locale(ctx)) }), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "browse"), "catalog:search")], [inlineButton(await t(ctx, "back"), "menu:main")]]) }); for (const sub of data.subscriptions.filter((s) => matches(listing!, s))) { if (sub.matchDays.filter((x) => x === day()).length >= 20) continue; sub.matchDays.push(day()); try { await ctx.api.sendMessage(sub.chatId, await t(ctx, "match", { listing: listingText(listing!, await locale(ctx)) }), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "view"), `catalog:view:${listing.id}`), inlineButton(await t(ctx, "pause"), `subs:toggle:${sub.id}`)]]) }); } catch {} } await writeDomain(ctx, data); });
composer.on("message:text", async (ctx, next) => { const text = ctx.message.text.trim(); const step = ctx.session.step; if (step === "submit:title") { ctx.session.draft = { ...ctx.session.draft, title: text }; await ask(ctx, "submit:description", "descriptionAsk", "descriptionHint"); return; } if (step === "submit:description") { ctx.session.draft = { ...ctx.session.draft, description: text }; await ask(ctx, "submit:price", "priceAsk", "priceHint"); return; } if (step === "submit:price") { const n = Number(text.replace(/[^0-9.]/g, "")); if (!Number.isFinite(n) || n <= 0) { await ctx.reply(await t(ctx, "priceInvalid")); return; } ctx.session.draft = { ...ctx.session.draft, price: n }; await ask(ctx, "submit:location", "locationAsk", "locationHint"); return; } if (step === "submit:location") { const description = String(ctx.session.draft?.description ?? "").toLowerCase(); const inferred = /house|дом|сад|yard|garden/.test(description) ? "house" : /room|комнат|shared/.test(description) ? "room" : "apartment"; ctx.session.draft = { ...ctx.session.draft, location: text }; ctx.session.step = "submit:type"; await ctx.reply(await t(ctx, "typeAsk", { type: await t(ctx, inferred as "apartment" | "house" | "room") }), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "apartment"), "submit:type:apartment"), inlineButton(await t(ctx, "house"), "submit:type:house")], [inlineButton(await t(ctx, "room"), "submit:type:room"), inlineButton(await t(ctx, "other"), "submit:type:other")], [inlineButton(await t(ctx, "back"), "menu:main")]]) }); return; } return next(); });
export default composer;
