import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { nextId, readDomain, writeDomain, type Subscription } from "../listing-data.js";
import { t } from "../i18n.js";
registerMainMenuItem({ label: "Мои подписки", labelKey: "menuSubs", data: "subs:list", order: 30 });
const composer = new Composer<Ctx>();
async function dashboard(ctx: Ctx) { const data = await readDomain(ctx); const mine = data.subscriptions.filter((s) => s.owner === String(ctx.from?.id ?? "")); if (!mine.length) { await ctx.reply(await t(ctx, "noSubs"), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "addSub"), "subs:add")], [inlineButton(await t(ctx, "back"), "menu:main")]]) }); return; } const items = await Promise.all(mine.map(async (s) => `${s.location || await t(ctx, "anyLocation")} · ${await t(ctx, s.active ? "active" : "paused")}`)); await ctx.reply(await t(ctx, "subsList", { items: items.join("\n") }), { reply_markup: inlineKeyboard([...await Promise.all(mine.map(async (s) => [inlineButton(await t(ctx, s.active ? "pause" : "resume"), `subs:toggle:${s.id}`)])), [inlineButton(await t(ctx, "addSub"), "subs:add")], [inlineButton(await t(ctx, "back"), "menu:main")]]) }); }
composer.callbackQuery("subs:list", async (ctx) => { await ctx.answerCallbackQuery(); await dashboard(ctx); });
composer.callbackQuery("subs:add", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.step = "subs:location"; ctx.session.draft = {}; await ctx.reply(await t(ctx, "subAskLocation"), { reply_markup: { force_reply: true, input_field_placeholder: await t(ctx, "subLocationHint") } }); });
composer.callbackQuery(/^subs:toggle:(s\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const data = await readDomain(ctx); const s = data.subscriptions.find((x) => x.id === ctx.match![1] && x.owner === String(ctx.from?.id ?? "")); if (!s) { await ctx.reply(await t(ctx, "subMissing")); return; } s.active = !s.active; await writeDomain(ctx, data); await ctx.reply(await t(ctx, s.active ? "subResumed" : "subPaused")); });
composer.callbackQuery("subs:match", async (ctx) => { await ctx.answerCallbackQuery(); await dashboard(ctx); });
composer.on("message:text", async (ctx, next) => { const text = ctx.message.text.trim(); if (ctx.session.step === "subs:location") { ctx.session.draft = { ...ctx.session.draft, location: /^(any|любой)$/i.test(text) ? undefined : text }; ctx.session.step = "subs:max"; await ctx.reply(await t(ctx, "subAskMax"), { reply_markup: { force_reply: true, input_field_placeholder: await t(ctx, "subMaxHint") } }); return; } if (ctx.session.step !== "subs:max") return next(); const max = /^(any|любой)$/i.test(text) ? undefined : Number(text.replace(/[^0-9.]/g, "")); if (max !== undefined && (!Number.isFinite(max) || max <= 0)) { await ctx.reply(await t(ctx, "subInvalid")); return; } const data = await readDomain(ctx); const d = ctx.session.draft as Record<string, unknown>; data.subscriptions.push({ id: nextId(data, "s"), owner: String(ctx.from?.id ?? ""), chatId: ctx.chat!.id, location: d.location as string | undefined, priceMax: max, active: true, matchDays: [] } satisfies Subscription); await writeDomain(ctx, data); ctx.session.step = "idle"; ctx.session.draft = undefined; await ctx.reply(await t(ctx, "subOn"), { reply_markup: inlineKeyboard([[inlineButton(await t(ctx, "manageSubs"), "subs:list")]]) }); });
export default composer;
