import { now, type Domain } from "./listing-data.js";

type Claims = { userId: string; csrf: string; exp: number };
const encoder = new TextEncoder();
const b64 = (data: Uint8Array) => btoa(String.fromCharCode(...data)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
const bytes = (text: string) => encoder.encode(text);
async function hmac(key: string | Uint8Array, value: string): Promise<Uint8Array> { const raw = typeof key === "string" ? bytes(key) : key; const source = raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.byteLength) as ArrayBuffer; const k = await crypto.subtle.importKey("raw", source, { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return new Uint8Array(await crypto.subtle.sign("HMAC", k, bytes(value))); }
const equal = (a: Uint8Array, b: Uint8Array) => a.length === b.length && a.reduce((ok, v, i) => ok && v === b[i], true);
export async function verifyInitData(initData: string, token: string): Promise<{ id: string } | null> { const p = new URLSearchParams(initData); const hash = p.get("hash"); const authDate = Number(p.get("auth_date")); p.delete("hash"); if (!hash || !Number.isFinite(authDate) || now().getTime() / 1000 - authDate > 86_400) return null; const lines = [...p.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `${k}=${v}`).join("\n"); const secret = await hmac("WebAppData", token); const expected = await hmac(secret, lines); const supplied = Uint8Array.from(atob(hash), (c) => c.charCodeAt(0)); const user = p.get("user"); try { const id = String((JSON.parse(user ?? "{}") as { id?: number }).id ?? ""); return id && equal(expected, supplied) ? { id } : null; } catch { return null; } }
export async function issueSession(userId: string, token: string): Promise<{ token: string; csrf: string }> { const csrf = b64(crypto.getRandomValues(new Uint8Array(18))); const payload = b64(bytes(JSON.stringify({ userId, csrf, exp: now().getTime() + 15 * 60_000 } satisfies Claims))); return { token: `${payload}.${b64(await hmac(token, payload))}`, csrf }; }
export async function readSession(value: string | null, token: string): Promise<Claims | null> { if (!value) return null; const [payload, signature] = value.split("."); if (!payload || !signature) return null; const expected = b64(await hmac(token, payload)); if (expected !== signature) return null; try { const claims = JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(payload.replace(/-/g, "+").replace(/_/g, "/")), c => c.charCodeAt(0)))) as Claims; return claims.exp > now().getTime() ? claims : null; } catch { return null; } }
export function webPage(): string { return `<!doctype html><html lang="ru"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Недвижимость</title><style>body{margin:0;background:#f5f7fb;color:#182334;font:16px system-ui}main{max-width:700px;margin:auto;padding:16px}header{display:flex;justify-content:space-between;align-items:center}button,select{padding:10px;border:0;border-radius:9px;background:#1769aa;color:white}article{background:white;margin:10px 0;padding:14px;border-radius:12px}</style><main><header><h1 id="title">Недвижимость</h1><select id="lang"><option value="ru">Русский</option><option value="en">English</option></select></header><p id="lead">Подходящие объявления и ваши подписки.</p><button id="refresh">Обновить</button><section id="list"></section></main><script src="https://telegram.org/js/telegram-web-app.js"></script><script>const T=window.Telegram?.WebApp;T?.ready();let token,csrf;const q=s=>document.querySelector(s);const words={ru:{title:'Недвижимость',lead:'Подходящие объявления и ваши подписки.',refresh:'Обновить',empty:'Объявлений пока нет.'},en:{title:'Real estate',lead:'Matching listings and your subscriptions.',refresh:'Refresh',empty:'No listings yet.'}};function setLang(){let w=words[q('#lang').value];for(let k in w)q('#'+k).textContent=w[k]}async function auth(){let r=await fetch('/webapp/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initData:T?.initData||''})});if(!r.ok)throw Error();({token,csrf}=await r.json())}async function load(){let r=await fetch('/webapp/listings',{headers:{authorization:'Bearer '+token,'x-csrf-token':csrf}});let x=await r.json();q('#list').innerHTML=x.listings.length?x.listings.map(l=>'<article><b>'+l.title+'</b><br>'+l.location+' · '+l.price+'</article>').join(''):'<article>'+words[q('#lang').value].empty+'</article>'}q('#refresh').onclick=load;q('#lang').onchange=()=>{setLang();load()};auth().then(load).catch(()=>q('#list').textContent='Не удалось войти. Откройте приложение из Telegram.');setLang()</script></html>`; }
export function webResponse(data: unknown, status = 200): Response { return Response.json(data, { status, headers: { "cache-control": "no-store" } }); }
export function publicListing(l: Domain["listings"][number]) { const { ownerChatId, owner, fingerprint, ...safe } = l; return safe; }
